"""Baby-step giant-step: solve g^x = h (mod p) in O(sqrt p).

The discrete logarithm problem — find the exponent x — has no known fast
solution, which is exactly why Diffie-Hellman and DSA rely on it. Baby-step
giant-step is the generic square-root attack: still exponential in the bit
length, but a large improvement on the O(p) brute force.

The trick is a meet in the middle. Write x = i*m - j with m = ceil(sqrt(n)).
Precompute all "baby steps" h * g^j for j in [0, m) into a hash table, then take
"giant steps" g^(i*m) and look each up. A match pins down x. It trades O(sqrt n)
memory for the speed.

O(sqrt n) time and memory, where n is the order of g.
"""

import math


def discrete_log(g: int, h: int, p: int, order: int | None = None) -> int | None:
    """Least non-negative x with g^x = h (mod p), or None if unsolvable."""
    g %= p
    h %= p
    n = order if order is not None else p - 1  # order of the group/element
    m = math.isqrt(n) + 1

    # Baby steps: table of h * g^j for j in [0, m).
    table: dict[int, int] = {}
    value = h % p
    for j in range(m):
        table.setdefault(value, j)  # keep the smallest j for a value
        value = value * g % p

    # Giant steps: g^(i*m), looking for a match.
    factor = pow(g, m, p)  # g^m
    giant = 1
    for i in range(m + 1):
        if giant in table:
            x = i * m - table[giant]
            if x >= 0 and pow(g, x, p) == h % p:  # guard against false hits
                return x
        giant = giant * factor % p
    return None


def main() -> None:
    # 2 is a primitive root mod 29; solve 2^x = 21.
    g, h, p = 2, 21, 29
    x = discrete_log(g, h, p)
    print(f"2^x = 21 (mod 29): x = {x}, check 2^{x} mod 29 = {pow(g, x, p)}")

    # Round-trip: pick x, compute h, recover x.
    cases = [(3, 7, 0), (5, 100003, 12345), (7, 1000003, 500000)]
    for g, p, secret in cases:
        h = pow(g, secret, p)
        recovered = discrete_log(g, h, p)
        print(f"  g={g} p={p}: hid x={secret}, recovered x={recovered}, "
              f"g^x matches: {pow(g, recovered, p) == h}")

    print("unsolvable when h is not in the subgroup generated by g:")
    # g=4 mod 11 generates {1,4,5,9,3}; 2 is not among them.
    print(f"  4^x = 2 (mod 11) -> {discrete_log(4, 2, 11, order=5)}")

    # This is the security assumption Diffie-Hellman rests on.
    print("Diffie-Hellman: public g^a and g^b reveal the secret only to an")
    print("attacker who can take a discrete log — infeasible for cryptographic p.")


if __name__ == "__main__":
    main()
